core/ui/src/public/Orders/index.tsx

- fix issue where infinite scroll for Orders with no filter was not loading more
- fix issue where clicking on All filter still shows the last selected filter as selected

[fix] infinite scroll for orders with no filters

---

core/sdk/src/CandyShop.ts
core/sdk/src/CandyShopModel.ts
core/ui/src/components/BuyModal/BuyModalConfirmed.tsx
core/ui/src/components/BuyModal/BuyModalDetail.tsx
core/ui/src/components/CancelModal/CancelModalDetail.tsx
core/ui/src/components/Order/index.tsx
core/ui/src/public/OrderDetail/index.tsx
core/ui/src/public/Stat/index.tsx

Allow user to set minimumFractionDigits and maximumFractionDigits as separate variables so that a price of 1.000 can be displayed as 1, while a price of 1.003 can be displayed as 1.003. In this case, priceDecimalsMin = 0 and priceDecimals = 3.
Currently, minimumFractionDigits and MaximumFractionDigits are both set to priceDecimals.
Same applies for volumeDecimals.

[feat] add min decimals setting

---

core/sdk/src/api/program/auction/buyNow.ts

the fail case will happen if the highest bidder trying to withdraw
before buy now is executing. This change move the withdrawBid case
after the buyNow.

Move withdrawBid to after buyNow

---

core/sdk/src/api/program/v1/auction/buyNow.ts
core/sdk/src/api/program/v2/auction/buyNow.ts

Due to the state change propagation delay, there
are situations where higgest bidder fails to
withdrawBid after buyNow. Remove the logic for now
and highest bidder will need to go back and withdrawBid
after buyNow. Will need to come up with better UI
solution to it.

[LIQ-613] Remove withdrawBid after buyNow

---

core/ui/src/public/Auction/create-auction-style.less

[fix] create auction styling

---

core/sdk/src/factory/program/v1/auction/bid.ts
core/sdk/src/factory/program/v1/auction/buyNow.ts
core/sdk/src/factory/program/v1/auction/settleAndDistribute.ts
core/sdk/src/factory/program/v2/auction/bid.ts
core/sdk/src/factory/program/v2/auction/buyNow.ts
core/sdk/src/factory/program/v2/auction/settleAndDistribute.ts

Compute units required varies depends on number of creators
in the NFT to be settled. This patch simply set the compute unit
close to max to avoid insufficient compute unit error.

Fine tune compute budget request

---

core/ui/src/components/CollectionFilter/index.tsx
core/ui/src/components/Search/style.less
core/ui/src/components/ShopFilter/index.tsx
core/ui/src/components/Tooltip/style.less
core/ui/src/public/Orders/index.less
core/ui/src/public/Orders/index.tsx
core/ui/src/style/order-filter.less
example/MarketplaceExample.tsx

- User can specify `search` and `filterSearch` argument to Orders component to show/hide search and filterSearch
- In example, show only collection filter (as most users do not use shop filter)
- Refine styling for search NFT box and filter bar

[feat] styling tweaks for search and sidebar

---

core/sdk/package.json
core/sdk/yarn.lock
core/types/package.json
core/ui/package.json
core/ui/yarn.lock

@liqnft/candy-shop-types -> 0.2.17
@liqnft/candy-shop-sdk -> 0.5.18
@liqnft/candy-shop -> 0.5.12

Bump core [types] [sdk] [ui] version

---

core/sdk/src/vendor/utils/validationUtils.ts

If the salesPeriod is 0, this means the sales will last forever until sell out.

[LIQ-833] Update edition drop mint condition check

---

core/cli/src/cli.ts
core/sdk/src/factory/program/v2/editionDrop/redeemNft.ts
core/sdk/src/idl/edition_drop.json

There are situations where after users commit a master edition NFT, they will close the token account. A change is added in the onchain program to make sure the check will be conducted against the mint account address directly instead of relying on the mint address in the token account. This change adds an extra ATA program argument into the redeemNft rpc handler, so the committer's master edition NFT token account can be re-initialized upon redemption.

Update ATA programId to redeemDrop

---

core/types/src/response/order.ts

Since chain reorg is a possibility in the EVM chains, introducing pending states for `filled` and `cancelled`. The state will transition into finalized once required number of confirmations is reached.

Add OrderStatus for EVM chains

---

core/ui/src/public/AuctionActivity/index.tsx
example/AuctionExample.tsx

Currently, the main UI components: AuctionActivity in public need candyShop: CandyShop as prop but the methods they called from sdk now can use without the CandyShop instance but just currencySymbol or partial infos.
To avoid breaking backward compatibility, I use union-types that can serve AuctionActivity with partial shop info without CandyShop instance.

[UI] Update-auction-activity-union-types

---

core/sdk/src/CandyShop.ts
example/constant/formConfiguration.ts

Due to the decommission of the Genesysgo free rpc, switching the default mainnet rpc back to the foundation rpc.
ref: https://twitter.com/GenesysGo/status/1583508696487067653?s=20&t=Zgy9izUpKzSvSjHA4orwWw

[sdk] Update default mainnet rpc url

---

core/sdk/src/factory/conveyor/eth/conveyor.ts
core/ui/src/components/BuyModal/index.tsx

According to https://docs.ethers.io/v5/troubleshooting/errors/#help-UNPREDICTABLE_GAS_LIMIT, there are 2 cases where the library will return `UNPREDICTABLE_GAS_LIMIT` error.
1. tx itself is destined to fail
2. tx is too complex to do gas estimation.
This change handles the case 2 by defaulting the gasLimit to a predefined level and let case 1 be processed as an error and propagate to the UI layer, with more verbose error message displayed, if available. 
LIQ-911

[sdk][ui] Enhance UNPREDICTABLE_GAS_LIMIT handling

---

core/sdk/src/factory/backend/OrderAPI.ts

LIQ-912
We couldn't get orders NFT from what's sold in SOL marketplace.
So I temporarily changed the code.
In this case, no matter in devnet or mainnet.
We should use "SOL" when we fetchOrders from backend.(Not use "devnet" or "mainnet-beta") 
So I did little mapping change. So that we can get orders.

[sdk] update fetchOrders blockchain in SOL

---

core/sdk/src/shop/base/BaseShop.ts
core/sdk/src/shop/eth/EthCandyShop.ts
core/sdk/src/vendor/config.ts

To initiate the EVM CandyShop, SDK will first need to know the backend to call to fetch the correct shop object. Therefore the call to configBaseUrl will preceed the new EthCandyShop function.
Since EthCandyShop extends BaseShop and BaseShop calls configBaseUrl as well in this constructor, there will be 2 configBaseCall calls for EthCandyShop for time being.

[sdk] Update configBaseUrl calling order

---

.eslintrc.json
core/sdk/src/CandyShopDrop.ts
core/sdk/src/factory/conveyor/eth/EthereumPort.ts
core/sdk/src/vendor/token/parseData.ts
core/sdk/src/vendor/utils/transactionUtils.ts

We should avoid using `!.` to bypass the TS compile for those values
could be null | undefine.

[chore] Set no-non-null-assertion lint rule as error

---

core/cli/src/cli.ts
core/sdk/src/CandyShopDrop.ts
core/sdk/src/factory/constants.ts
core/sdk/src/factory/conveyor/sol/types/shop.type.ts
core/sdk/src/factory/conveyor/sol/v2/editionDrop/commitNft.ts
core/sdk/src/factory/conveyor/sol/v2/editionDrop/mintPrintWithInfo.ts
core/sdk/src/idl/edition_drop.json
core/sdk/src/shop/sol/CandyShop.ts
core/sdk/src/shop/sol/CandyShopModel.ts
core/sdk/src/vendor/utils/programUtils.ts
core/ui/src/components/Drop/Confirm/index.tsx
core/ui/src/components/Drop/Form/index.tsx

Adding a `hasRedemption` option into the commitNft operation, and `info` field to the mintPrint operation.
`hasRedemption` will be used to indicate whether a vault should have the ability to link its edition NFTs to some IRL product or services, and the `info` field is used as hashed userInput for redemption validation purposes.
Note:
The shopCommitNft operation will be non-backward compatible with the newly added `hasRedemption` field.
LIQ-1055

[sdk][cli] mintPrintWithInfo

---

core/ui/src/components/Auction/AuctionForm/index.tsx
core/ui/src/components/Drop/Form/index.tsx
core/ui/src/components/Tooltip/style.less
core/ui/src/public/Auction/CreateAuction.tsx

LIQ-1173 LIQ-1179
1. [feat] edition drop can pass salesPeriod = 0 when create.
2. [feat] auction can set endtime when create.
3. [fix] change back @candy-shop-popover-background color to #fff, and set ToolTip background-color to #1a2029.
if not, the popover background color will be wrong.
[LIQ-1173]: https://liqnft.atlassian.net/browse/LIQ-1173?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LIQ-1179]: https://liqnft.atlassian.net/browse/LIQ-1179?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ui] add edition drop unlimited sales period and auction endtime when create

---

core/sdk/src/CandyShopPay.ts
core/sdk/src/factory/backend/PaymentAPI.ts
core/sdk/src/shop/eth/EthShopModel.ts
core/types/src/payment/PaymentModel.ts
core/types/src/payment/PaymentResponse.ts

[LIQ-1192]
types
- Update checkPaymentAvailability API to base on tokenMint
- Update fetchTokenFiatMoneyPrice API to base on tokenMint
- Add separate types for CreatePayment and ConfirmPayment
sdk
- Update relevant backend methods
- Expose CreateWertPayment from sdk since the OrderPayloadResponse
is in /factory/conveyor/eth
[LIQ-1192]: https://liqnft.atlassian.net/browse/LIQ-1192?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[core] Add Wert credit card Payment support for EVM in types & sdk
