LIQNFT/candy-shop

src/api/backend/OrderAPI.ts
src/components/BuyModal/BuyModalDetail.tsx
src/components/BuyModal/style.less
src/components/CancelModal/CancelModalConfirm.tsx
src/components/CancelModal/CancelModalDetail.tsx
src/components/CancelModal/index.tsx
src/components/CancelModal/style.less
src/components/Nft/index.tsx
src/components/SellModal/index.tsx
src/core/CandyShop.tsx
src/core/Sell.tsx
tsdx.config.js

feat: cancel modal and api cancel

UI cancel modal

---

.eslintrc
example/CandyShopContent.tsx
src/api/program/buyAndExecuteSale.ts
src/api/program/withdrawRevenue.ts
src/api/utils.ts
src/components/BuyModal/BuyModalConfirmed.tsx
src/components/BuyModal/BuyModalDetail.tsx
src/components/BuyModal/index.tsx
src/components/CancelModal/CancelModalConfirm.tsx
src/components/CancelModal/CancelModalDetail.tsx
src/components/CancelModal/index.tsx
src/components/SellModal/index.tsx
src/core/Orders.tsx
src/core/Sell.tsx

check all warnings issue with un-use variables, missing deps from react hooks

fix warnings

---

example/CandyShopContent.tsx
example/package.json
src/core/CandyShop.tsx
src/core/Stat/index.tsx
src/core/Stat/style.less
src/index.tsx
yarn.lock

feat:stat component

---

package.json
src/api/program/buyAndExecuteSale.ts
src/api/program/cancel.ts
src/api/program/create.ts
src/api/program/sell.ts
src/api/program/submitTx.ts
src/api/program/withdrawRevenue.ts
yarn.lock

Since sendRawTransaction might get dropped by node, implemented
retry.

[LIQ-395] Add retry logic

---

src/api/fetchMetadata.ts
src/api/fetchNftsFromWallet.ts

Remove default metadata + remove wrong inclusion of non-nft token account

Fix metadata bug

---

src/components/BuyModal/BuyModalDetail.tsx
src/components/BuyModal/index.tsx
src/components/BuyModal/style.less
src/components/Tag/index.tsx

[LIQ-425] Show attributes in buy modal

---

package.json
src/api/backend/OrderAPI.ts
src/assets/IconChevronDown.tsx
src/assets/IconChevronUp.tsx
src/components/Dropdown/index.tsx
src/core/CandyShop.tsx
src/core/Orders.tsx
yarn.lock

The photo shows an outdated screenshot, I made the selected label's text purple in the latest commit

[LIQ-424] Sort orders

---

src/components/BuyModal/BuyModalDetail.tsx
src/components/CancelModal/CancelModalConfirm.stories.tsx
src/components/CancelModal/CancelModalDetail.stories.tsx
src/components/LiqImage/index.tsx
src/components/Order/Order.stories.tsx
src/components/Order/index.tsx
src/core/CandyShop.tsx
src/core/Sell.tsx
src/core/Stat/Stat.stories.tsx
src/stories/mocks.ts

When running `yarn build` or `yarn start`, current storybook relevant files will have errors that is confusing from other real error from candy-shop. This PR will eliminate those errors by properly extending the mock class. 
Let me know if anything missed or misplacement.

[fix] Fix stroybook's confusing error msgs

---

lib/src/api/program/buyAndExecuteSale.ts

Unfortunately if bundled together as 1 Tx will run
out of compute units

Separate AtaAccountCreationTx from BuyAndExecute

---

README.md
example/CandyShopContent.tsx
lib/src/api/backend/OrderAPI.ts
lib/src/api/getIdentifier.ts
lib/src/api/index.ts
lib/src/components/InfiniteOrderList/index.tsx
lib/src/core/CandyShop/index.tsx
lib/src/core/Orders/index.tsx
lib/src/index.tsx

- User can add filter by collection component to Orders component
- User can use getIdentifier method to get identifier for an NFT collection
- Update README for claim revenue, whitelist NFT collection, single NFT component and filter by collection features

Add left filter bar

---

sdk/src/config/index.ts
sdk/src/index.ts

I have tested with interceptorEvents = eventId, but seem configBaseUrl function is called in parallel, we can't remove all event. So I make it as a list id, and remove that list

fix duplicate axios interceptor events

---

core/ui/src/components/BuyModal/BuyModalDetail.tsx
core/ui/src/components/CancelModal/CancelModalDetail.tsx
core/ui/src/components/InfiniteOrderList/index.tsx
core/ui/src/components/Nft/index.tsx
core/ui/src/components/Order/index.less
core/ui/src/components/Order/index.tsx
core/ui/src/index.less
core/ui/src/public/OrderDetail/index.tsx
core/ui/src/public/Orders/index.less
core/ui/src/public/Orders/index.tsx
core/ui/src/utils/ErrorHandler.ts

cancel listing flow is same as Sell component

listed for sell in Orders

---

core/sdk/src/CandyShop.ts
core/sdk/src/api/program/InsBuyAndExecuteSale.ts
core/sdk/src/api/program/buyAndExecuteSale.ts
core/sdk/src/api/program/cancel.ts
core/sdk/src/api/utils.ts
core/sdk/src/utils/error.ts
core/sdk/src/utils/index.ts
core/sdk/yarn.lock
core/ui/src/components/BuyModal/index.tsx
core/ui/src/components/CancelModal/CancelModalDetail.tsx
core/ui/src/components/SellModal/index.tsx
core/ui/src/public/OrderDetail/index.tsx
core/ui/src/utils/ErrorHandler.ts

Fulfills ticket [LIQ-494](https://liqnft.atlassian.net/browse/LIQ-494l)

Add pre-emptive checks and error-handling to sdk

---

core/sdk/package.json
core/sdk/yarn.lock
core/ui/package.json
core/ui/yarn.lock

release 0.4.35

---

core/ui/src/public/Sell/index.tsx

Make if condition for showing Loading, NFTs or Empty state in Sell modal more readable and robust

[fix] if condition on sell component

---

core/sdk/src/api/program/InsBuyAndExecuteSale.ts
core/sdk/src/api/program/buyAndExecuteSale.ts
core/sdk/src/api/program/cancel.ts
core/sdk/src/api/program/sell.ts
core/sdk/test/e2eSol.spec.ts
core/sdk/test/e2eToken.spec.ts

Second part of [LIQ-521](https://liqnft.atlassian.net/browse/LIQ-521)

[sdk] Update sdk ix calls to use new Anchor api

---

core/sdk/package.json
core/sdk/src/api/utils.ts
core/sdk/test/e2eSol.spec.ts
core/ui/package.json
core/ui/yarn.lock

Use safeAwait so the error does not break the transaction
crafting flow.

Fix token account delegate check

---

core/sdk/src/api/program/InsBuyAndExecuteSale.ts
core/sdk/src/api/program/buyAndExecuteSale.ts
core/sdk/src/api/program/sell.ts
core/sdk/src/api/utils.ts
core/sdk/src/utils/promiseUtils.ts
core/sdk/test/e2eToken.spec.ts

[LIQ-526](https://liqnft.atlassian.net/browse/LIQ-526)

[sdk] Add ix to revoke seller treasurty ata delegate before sell tx (if exists)

---

core/ui/package.json
core/ui/yarn.lock

- candy-shop: 0.4.39
- candy-shop-sdk: 0.4.27

Release candy-shop and candy-shop-sdk

---

core/cli/README.md
core/cli/package.json
core/cli/src/cli.ts
core/cli/src/helper/account.ts
core/cli/tsconfig.json
core/cli/yarn.lock

- add `sellMany` and `cancelMany` functions that take an array of token mints as input
- derivate token account from wallet address for `sell` and `cancel`.

[core/cli] update and add sell many function

---

bump.ts
core/cli/package.json
core/sdk/package.json
core/ui/package.json
core/ui/yarn.lock
package.json
publish.sh
yarn.lock

Strawman publish script to reduce publishing pain (NEEDS TESTING)
TODO: how to prevent publish when there are any compile warnings in yarn build
Example usage:
1. Bump SDK and UI version and publish SDK and UI `bash publish.sh sdk=patch ui=patch`
2. Bump UI version and publish UI `bash publish.sh ui=patch`
3. specify which component to publish (sdk, ui)
4. specify which version to bump (patch, minor, major)

[chore] publish script

---

core/cli/package.json
core/sdk/package.json
core/types/package.json
core/ui/package.json
core/ui/yarn.lock

- @liqnft/candy-shop@0.4.44
- @liqnft/candy-shop-sdk@0.4.32

Bump version

---

core/cli/package.json
core/sdk/package.json
core/ui/package.json
core/ui/yarn.lock

- @liqnft/candy-shop@0.4.45
- @liqnft/candy-shop-sdk@0.4.33

release v0.4.45

---

core/cli/package.json
core/sdk/package.json
core/ui/package.json
core/ui/yarn.lock

- @liqnft/candy-shop@0.4.46
- @liqnft/candy-shop-sdk@0.4.34

release v0.4.46

---

core/cli/package.json
core/sdk/src/CandyShop.ts
core/sdk/src/CandyShopModel.ts
core/sdk/src/api/model.ts
core/sdk/src/api/program/marketplace/updateCandyShop.ts
core/sdk/src/api/utils.ts
core/sdk/src/candy_shop.json

Note: Idl still needs update with new program ix

Add update candy shop ix to CandyShop sdk class

---

core/sdk/package.json
core/sdk/src/CandyShop.ts
core/sdk/src/api/backend/OrderAPI.ts
core/sdk/src/api/program/marketplace/insBuyAndExecuteSale.ts

Need to update code when CandyShopV2 is ready

Add tentative CandyShopIns support

---

core/cli/package.json
core/sdk/package.json
core/sdk/yarn.lock
core/types/package.json
core/ui/package.json
core/ui/yarn.lock

@liqnft/candy-shop-types@0.2.0
@liqnft/candy-shop-sdk@0.5.1
@liqnft/candy-shop@0.5.0

Upgrade candyshop version

---

core/ui/package.json
core/ui/yarn.lock

Fixes the model-viewer import issue by downgrading to model-viewer@1.8.0

Bump version to v0.5.3

---

core/sdk/package.json
core/sdk/yarn.lock
core/types/package.json

Bump SDK to 0.5.3

---

core/ui/src/components/BuyModal/index.tsx

Since its already checked in SDK level, removed from UI package.

[LIQ-652] Remove buy NFT balance check from UI

---

core/ui/package.json

Bump core [ui] version

---

core/sdk/package.json
core/sdk/yarn.lock
core/types/package.json
core/ui/package.json
core/ui/yarn.lock

@liqnft/candy-shop-types -> 0.2.10
@liqnft/candy-shop-sdk -> 0.5.11
@liqnft/candy-shop -> 0.5.7

Bump core [types] [sdk] [ui] version

---

core/sdk/package.json
core/sdk/src/factory/program/v1/auction/buyNow.ts
core/sdk/src/factory/program/v1/auction/requestExtraComputeIx.ts
core/sdk/src/factory/program/v1/auction/settleAndDistribute.ts
core/sdk/src/factory/program/v2/auction/buyNow.ts
core/sdk/src/factory/program/v2/auction/requestExtraComputeIx.ts
core/sdk/src/factory/program/v2/auction/settleAndDistribute.ts
core/sdk/yarn.lock

Need to install @solana/web3.js separately as anchor
does not depends on the @solana/web3.js that contains ComputeBudgetProgram

Add Request Compute Unit

---

core/sdk/src/factory/backend/OrderAPI.ts
core/types/src/query/query.ts
core/ui/src/public/Orders/index.less
core/ui/src/public/Orders/index.tsx

typo
LIQ-657 search nft by name

LIQ-657 search nft by name

---

core/sdk/package.json
core/sdk/yarn.lock
core/types/package.json
core/ui/package.json
core/ui/yarn.lock

@liqnft/candy-shop-types -> 0.2.14
@liqnft/candy-shop-sdk -> 0.5.15

Bump core [types] [sdk] version

---

core/ui/src/components/CollectionFilter/index.tsx
core/ui/src/components/ShopFilter/index.tsx
core/ui/src/public/Orders/index.tsx

Can't search collection and shop uppercase name 
Missing hide search box in empty filter option

bug: manual search logic

---

core/sdk/src/CandyShopDrop.ts

Since browser does not support Buffer natively, replace buffer
with Uint8Array.

Remove Buffer usage

---

core/sdk/src/factory/program/v2/editionDrop/commitNft.ts
core/sdk/src/factory/program/v2/editionDrop/enterpriseCommitNft.ts
core/sdk/src/vendor/error.ts
core/sdk/src/vendor/token/fetchMetadata.ts
core/sdk/src/vendor/utils/validationUtils.ts

Editon drop feature only allow 10K edition to be printed.

Add master edition max supply check

---

core/sdk/src/vendor/utils/validationUtils.ts

The fix accommodates the whitelist time period check

Update check mint print period check

---

core/ui/src/components/Auction/AuctionForm/index.tsx
core/ui/src/components/Drop/Form/index.tsx
core/ui/src/components/Drop/List/VaultCountdown.tsx
core/ui/src/utils/getDropLabel.ts

LIQ-783, LIQ-784

---

core/sdk/test/e2eEditionSol.spec.ts

Due to the change in #417, this change updates the connection usage in testcases.

[sdk] update test connection

---

core/ui/src/components/Drop/List/DropFooter.tsx
core/ui/src/components/Drop/List/style.less

- Move the price to the left and make font size consistent with the regular drop.
- Remove MINT PRICE.

[ui] change edition drop styling

---

core/sdk/src/factory/conveyor/eth/blockchain.ts
core/sdk/src/factory/conveyor/eth/conveyor.ts

[fix] default gas limit when estimateGasFee fails

---

core/sdk/src/CandyShopDrop.ts

Update code based on the condition upgrade from metaplex.
ref: https://github.com/metaplex-foundation/metaplex-program-library/commit/33808b73079eda8bdaee7c67bf9d8f9b9eefd514

[fix] Set freeze authority for new mint

---

core/sdk/src/factory/backend/NftAPI.ts
core/sdk/src/vendor/token/fetch.type.ts
core/sdk/src/vendor/token/fetchEvmNftsFromWallet.ts
core/types/src/query/query.ts
core/types/src/response/common.ts
core/ui/src/hooks/useUserNfts.ts
core/ui/src/market/EthStore.ts
core/ui/src/market/SolStore.ts
core/ui/src/market/catalog.ts

[sdk][ui] Fetch EVM wallet filtering

---

core/sdk/src/factory/backend/DropAPI.ts
core/types/src/query/query.ts

[LIQ-916]
[LIQ-916]: https://liqnft.atlassian.net/browse/LIQ-916?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[core] filter drop by collectionKey

---

core/cli/src/cli.ts
core/cli/yarn.lock
core/sdk/src/CandyShopDrop.ts
core/sdk/src/shop/sol/CandyShop.ts
core/sdk/src/shop/sol/CandyShopModel.ts

LIQ-914
Add a cli "mintAllPrint"
Mint all edition drop nfts in one time and generate a json file to record nfts address for cli sellMany to use.

[cli] mint all edition drop nfts

---

core/ui/src/hooks/useUserNfts.ts

[ui] get current NFTs from trade websocket

---

example/sol/constants/formConfiguration.ts

[example] update mainnet rpc

---

core/ui/src/components/SellModal/index.tsx
core/ui/src/public/Sell/index.tsx

[ui] decimal checking for selling NFT

---

core/sdk/src/shop/eth/EthCandyShop.ts
core/sdk/src/vendor/token/fetchMetadata.ts

[feat] Add ERC1155 support

---

example/eth/EthExample.tsx
example/sol/SolExample.tsx

[LIQ-992]
[LIQ-992]: https://liqnft.atlassian.net/browse/LIQ-992?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[example] show invalid shop config when access page

---

core/ui/src/components/Price/index.tsx

[ui] fix Auction show winning bid correctly

---

core/ui/src/components/Auction/AuctionModal/style.less
core/ui/src/components/Drop/Form/style.less

[ui] fix auction color

---

core/sdk/src/shop/base/BaseShopModel.ts
core/sdk/src/shop/eth/EthCandyShop.ts
core/sdk/src/shop/sol/CandyShop.ts

Make the connectionUrl can not be undefined, it should be provided
in shop init stage.

[sdk] Refactor connectionUrl for ShopSettings

---

core/ui/src/components/CollectionFilter/index.tsx
core/ui/src/components/Drop/List/index.tsx
core/ui/src/components/Drop/List/style.less
core/ui/src/components/Empty/index.less
core/ui/src/components/ShopFilter/index.tsx
core/ui/src/index.less
core/ui/src/utils/getDropLabel.ts

[ui] various styling fixes

---

core/ui/src/components/Auction/AuctionModal/AuctionModalDetail.tsx

[ui] add space between the price

---

core/ui/src/components/Dropdown/index.tsx
core/ui/src/hooks/useClickOutside.ts

[ui] refactor useClickOutside to bind hook with `ref` directly

---

core/sdk/src/factory/conveyor/eth/EthereumPort.ts
core/sdk/src/factory/conveyor/eth/types/order.type.ts

[sdk] add API for fulfillOrder payload

---

core/sdk/src/factory/conveyor/eth/EthereumPort.ts
core/sdk/src/shop/eth/EthCandyShop.ts

[sdk] add getNftPurchasePayload

---

core/sdk/src/CandyShopDrop.ts
core/sdk/src/shop/sol/CandyShop.ts
core/sdk/src/shop/sol/CandyShopModel.ts
core/ui/src/components/Drop/Confirm/index.tsx
core/ui/src/components/Drop/Form/index.tsx
core/ui/src/components/Form/Input.tsx

[LIQ-1241]
[LIQ-1241]: https://liqnft.atlassian.net/browse/LIQ-1241?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ui][sdk] redemption description

---

core/sdk/src/CandyShopInfoAPI.ts
core/sdk/src/factory/backend/OrderAPI.ts
core/sdk/src/factory/backend/ShopAPI.ts
core/sdk/src/factory/backend/utils.ts
core/sdk/src/shop/eth/EthCandyShop.ts
core/sdk/src/shop/sol/CandyShop.ts
core/ui/src/public/Orders/index.tsx
core/ui/src/public/Stat/index.tsx

LIQ-1211
- **New feature**
1. update the record from chain=MUMAI to `GOERLI` in your staging db
2. fire the request in the SDK

[core] specify which chain to create shop
